server:
  port: 9101

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cgsystem?serverTimezone=UTC
      username: root
      password: 123456
  application:
    name: comment-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # 配置Nacos注册中心地址
    sentinel:
      transport:
        dashboard: localhost:8858 # 添加监控页面地址即可

seata:
  service:
    vgroup-mapping:
      # 这里需要对事务组做映射，默认的分组名为 应用名称-seata-service-group，将其映射到default集群
      # 这个很关键，一定要配置对，不然会找不到服务
      comment-service-seata-service-group: default
    grouplist:
      default: localhost:8868