server:
  port: 8101

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cgsystem?serverTimezone=UTC
      username: root
      password: 123456
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # 配置Nacos注册中心地址
    sentinel:
      eager: true
      transport:
        dashboard: localhost:8858 # 添加监控页面地址即可
        port: 8715